create type public.app_role as enum ('user','admin');
create type public.content_status as enum ('draft','pending_review','published','rejected','hidden','archived');
create type public.visibility as enum ('public','members');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, first_name text, role app_role not null default 'user', is_approved_member boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.prayer_requests (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete set null, title text not null, body text not null, category text not null default 'general', anonymous boolean not null default true, urgent boolean not null default false, status content_status not null default 'pending_review', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.prayer_request_reports (id uuid primary key default gen_random_uuid(), prayer_request_id uuid not null references public.prayer_requests(id) on delete cascade, reporter_id uuid references auth.users(id) on delete set null, reason text not null, status content_status not null default 'pending_review', created_at timestamptz not null default now());
create table public.events (id uuid primary key default gen_random_uuid(), title text not null, event_date date not null, event_time time, location text, description text not null, visibility visibility not null default 'public', status content_status not null default 'pending_review', created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.devotionals (id uuid primary key default gen_random_uuid(), title text not null, body text not null, scripture_reference text, author text, status content_status not null default 'draft', created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.sermon_notes (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, scripture_reference text, notes_body text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.saved_verses (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, translation text not null default 'KJV', book text not null, chapter int not null, verse int not null, text text not null, note text, created_at timestamptz not null default now());
create table public.testimonies (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete set null, title text not null, body text not null, anonymous boolean not null default true, status content_status not null default 'pending_review', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.membership_requests (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, reason text, status content_status not null default 'pending_review', reviewed_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.private_community_posts (id uuid primary key default gen_random_uuid(), title text not null, body text not null, visibility visibility not null default 'members', status content_status not null default 'draft', created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.statement_of_faith_sections (id uuid primary key default gen_random_uuid(), title text not null, body text not null, sort_order int not null default 0, status content_status not null default 'published', updated_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.notification_preferences (user_id uuid primary key references auth.users(id) on delete cascade, prayer_updates boolean not null default true, event_reminders boolean not null default true, devotionals boolean not null default true, push_enabled boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') $$;
create or replace function public.is_approved_member() returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.profiles where id = auth.uid() and (is_approved_member or role = 'admin')) $$;
